name: Build PKPrac Mod

on:
  push:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'libs/**'
  pull_request:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'libs/**'
  release:
    types: [published]

jobs:
  build:
    if: github.event_name != 'release' # skip on release event
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: chmod +x ./gradlew
      - run: ./gradlew build

      - name: Upload built mod jar
        uses: actions/upload-artifact@v4
        with:
          name: pkprac-mod
          path: build/libs/PKPracMod.jar

  release:
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: chmod +x ./gradlew
      - run: ./gradlew build
