name: Build PKPrac Mod 

on:
  push:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'gradle/**'
      - 'gradlew*'
  pull_request:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'gradle/**'
      - 'gradlew*'
  release:
    types: [published]

jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Setup workspace
        run: ./gradlew setupDecompWorkspace

      - name: Build mod with Gradle
        run: ./gradlew build --stacktrace --info

      - name: Upload built mod jar
        uses: actions/upload-artifact@v4
        with:
          name: pkprac-mod
          path: build/libs/*.jar
