name: Build PKPrac Mod

on:
  push:
    paths:
      - 'src/**'
      - 'gradle/**'
      - 'gradlew*'
      - '.github/workflows/gradle-publish.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'gradle/**'
      - 'gradlew*'
      - '.github/workflows/gradle-publish.yml'
  release:
    types: [published]

jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Xmx3g -XX:MaxMetaspaceSize=512m

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Cache Gradle Pls save me
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Cache setupDecompWorkspace
        id: cache-setup-decomp-workspace
        uses: actions/cache@v4
        with:
          path: |
            .gradle
          key: setup-decomp-workspace-${{ runner.os }}-${{ hashFiles('build.gradle') }}

      - name: Setup workspace
        if: steps.cache-setup-decomp-workspace.outputs.cache-hit != 'true'
        run: ./gradlew setupDecompWorkspace --no-daemon -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=512m"

      - name: Build mod with Gradle
        run: ./gradlew build --stacktrace --info

      - name: Upload built mod jar
        uses: actions/upload-artifact@v4
        with:
          name: pkprac-mod
          path: build/libs/*.jar